[package]
name = "ursula"
version = "0.1.0"
authors = ["Patrick Kollodzik <patrick.kollodzik@sinnerschrader.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
svg = "0.6.0"
regex = "1.3.4"